### ISSUE TITLE
Release v0.3.1

### ISSUE THREAD

**Issue by OTL** [Eljay/assimp-sys#21]
Hi,
If you could release current master as v0.3.1, I can develop my programs without [patch.crates-io] on my macbook. It will help me a lot.

**Comment by Eljay** [comment]
Hi, I've published v0.3.1 of assimp and assimp-sys.

**Comment by OTL** [comment]
thanks a lot!

2017/11/04 7:48 "Lee Jeffery" <notifications@github.com>:
